### ISSUE TITLE
sydney.py

### ISSUE THREAD

**Issue by fabHAgithub** [tiernan1979/BingChatAI#1]
How to install this?? I don't understand a lot.
![image](https://github.com/tiernan1979/BingChatAI/assets/85220859/8d6874b3-2304-4725-bfc6-bb661659c854)

**Comment by tiernan1979** [comment]
What operating system is your home assistant running on ? 

Does your home assistant have internet access ?

Sydney.py comes from https://github.com/vsakkas/sydney.py
There is a potential that this version has been pulled from downloading.
I have created a beta version to test out the latest sydney.py
It appears to be still functional.

To download this in HAC's go to the HAC page and integrations.
1.  Find Bing Chat AI and click on it.
2.  Hit the 3 dots in the top right corner and select Re-Download
3.  Enable Show Beta versions
4.  Select 0.1.3-beta one and hit download
5.  Restart Home Assistant
